import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';

class ReportService {
 
  Map<String, dynamic> generateReport(
      List<Map<String, dynamic>> records, DateTime fromDate, DateTime toDate) {
    final filteredRecords = records.where((record) {
      final recordDate = DateTime.parse(record['date']);
      return !recordDate.isBefore(fromDate) && !recordDate.isAfter(toDate);
    }).toList();

    if (filteredRecords.isEmpty) {
      throw Exception('No records found for the selected date range');
    }

    final totalSteps = filteredRecords.fold<int>(
        0, (sum, record) => sum + (record['steps'] as int));
    final totalCalories = filteredRecords.fold<int>(
        0, (sum, record) => sum + (record['calories'] as int));
    final totalWater = filteredRecords.fold<int>(
        0, (sum, record) => sum + (record['water'] as int));

    final avgSteps = totalSteps / filteredRecords.length;
    final avgCalories = totalCalories / filteredRecords.length;
    final avgWater = totalWater / filteredRecords.length;

    final bestStepsDay = filteredRecords.fold<Map<String, dynamic>>(
        filteredRecords.first,
        (best, current) =>
            (current['steps'] as int) > (best['steps'] as int) ? current : best);
    final bestCaloriesDay = filteredRecords.fold<Map<String, dynamic>>(
        filteredRecords.first,
        (best, current) => (current['calories'] as int) > (best['calories'] as int)
            ? current
            : current);
    final bestWaterDay = filteredRecords.fold<Map<String, dynamic>>(
        filteredRecords.first,
        (best, current) =>
            (current['water'] as int) > (best['water'] as int) ? current : best);

    return {
      'fromDate': fromDate,
      'toDate': toDate,
      'records': filteredRecords,
      'totalSteps': totalSteps,
      'totalCalories': totalCalories,
      'totalWater': totalWater,
      'avgSteps': avgSteps,
      'avgCalories': avgCalories,
      'avgWater': avgWater,
      'bestStepsDay': bestStepsDay['steps'],
      'bestCaloriesDay': bestCaloriesDay['calories'],
      'bestWaterDay': bestWaterDay['water'],
    };
  }

  
  Future<File> saveReport(Map<String, dynamic> report) async {
    final content = _generateTextReport(report);
    final directory = await getApplicationDocumentsDirectory();
    final file = File(
        '${directory.path}/healthmate_report_${DateTime.now().millisecondsSinceEpoch}.txt');

    await file.writeAsString(content);
    return file;
  }

 
  Future<void> shareReport(File file) async {
    await Share.shareXFiles([XFile(file.path)]);
  }

  String _generateTextReport(Map<String, dynamic> report) {
    final buffer = StringBuffer();
    final dateFormat = DateFormat('dd MMM yyyy');

    buffer.writeln('HealthMate Report');
    buffer.writeln('==================');
    buffer.writeln();
    buffer.writeln(
        'Report Period: ${dateFormat.format(report['fromDate'])} - ${dateFormat.format(report['toDate'])}');
    buffer.writeln('Generated on: ${DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now())}');
    buffer.writeln();
    buffer.writeln('Summary Statistics');
    buffer.writeln('------------------');
    buffer.writeln('Total Steps: ${_formatNumber(report['totalSteps'])}');
    buffer.writeln('Total Calories: ${_formatNumber(report['totalCalories'])}');
    buffer.writeln('Total Water: ${_formatNumber(report['totalWater'])} ml');
    buffer.writeln('Average Steps/Day: ${report['avgSteps'].toStringAsFixed(0)}');
    buffer.writeln('Average Calories/Day: ${report['avgCalories'].toStringAsFixed(0)}');
    buffer.writeln('Average Water/Day: ${report['avgWater'].toStringAsFixed(0)} ml');
    buffer.writeln('Best Steps Day: ${_formatNumber(report['bestStepsDay'])}');
    buffer.writeln('Best Calories Day: ${_formatNumber(report['bestCaloriesDay'])}');
    buffer.writeln('Best Water Day: ${_formatNumber(report['bestWaterDay'])} ml');
    buffer.writeln();
    buffer.writeln('Daily Records');
    buffer.writeln('-------------');

    for (final record in report['records']) {
      buffer.writeln(
          '${dateFormat.format(DateTime.parse(record['date']))}: Steps: ${_formatNumber(record['steps'])}, Calories: ${_formatNumber(record['calories'])}, Water: ${_formatNumber(record['water'])} ml');
    }

    buffer.writeln();
    buffer.writeln('Generated by HealthMate App');

    return buffer.toString();
  }

  String _formatNumber(int number) {
    if (number >= 1000) {
      return '${(number / 1000).toStringAsFixed(1)}k';
    }
    return number.toString();
  }
}